### PR TITLE
Update _index.adoc

### PR DESCRIPTION
**Pull request by pauloneyleite**
...just a typo ;-)

### CODE REVIEW

**Comment by pauamma** [comment]
I don't think it's a typo ("take on board" means accept, learn, make use of something new), so the change you suggest doesn't look right, but I agree that use isn't clear. Perhaps "make use of"?

**Comment by pauloneyleite** [comment]
Interesting, I can agree to that...I was thinking about "complexity
warning", thus "broad", being it for newcomers..."make use of" sharpens the
angle on "learn/use as you go", makes perfect sense! Nice...

Paulo Ney Leite
Language Coach & Technologist
Coach para Fluência em Inglês & Tecnólogo
+55 75 998583406
https://sites.google.com/view/achaveinglesa/home

**Comment by pauamma** [comment]
> Interesting, I can agree to that...I was thinking about "complexity warning", thus "broad", being it for newcomers..."make use of" sharpens the angle on "learn/use as you go", makes perfect sense! Nice...

I'll let you update your pull request, then. (I can't change or merge your request.)

Oh, and thanks for taking the time to submit it, BTW.

**Comment by debdrup** [comment]
I think it'd be better to close this PR and open a new one with the new fix.

**Comment by dbaio** [comment]
Hi.

As this PR has been stale for a while, I'm closing it.

Please reopen it or open a new PR anytime you want.

Thank you!

**Pull request closed without merging**
