### PR TITLE
Status: 2023q3: Wifibox: corrections, changes

### PR DESCRIPTION
**Pull request by grahamperrin**
Add the missing URL parts of the links lines.

Americanisation of the heading, consistent with past status reports.

~~Create subheadings for system requirements, and for features.~~ 

~~Make more use of normal paragraphs, less use of bullet points.  Reorder things, to add clarity.~~

~~Conciseness and other suggested changes/corrections.~~

### CODE REVIEW

**Comment by grahamperrin** [comment]
@pgj for your consideration. Thank you.

**Review by lsalvadore — COMMENTED** [review]
I approve the Links part (once the typo is fixed).

The rest should be approved by the original author @pgj.

**Comment by pgj** [comment]
Thank you.  I am not sure I understand why it was necessary to change the text structure beyond style, formatting, and grammar fixes.  For example, the description says "less use of bullet points" while it replaces the original 6 bullet points with 8.  Is there a very specific style that is expected for the entries?

**Comment by lsalvadore** [comment]
No @pgj, there is no very specific style expected beside what you can find at https://docs.freebsd.org/en/books/fdp-primer/writing-style/ and https://docs.freebsd.org/en/articles/freebsd-status-report-process/#_instructions_for_writers. @grahamperrin found the structure he proposed clearer and made a suggestion. You are free to reject it if you liked your original text more.

**Comment by pgj** [comment]
Sorry, I was not evident for me that this is a suggestion.  My original pull request was closed and then I was thanked here for my consideration -- but nothing else.

If there is no other special consideration I should have complied, then yes, please keep my original structure of text.  Do not get me wrong, I appreciate the effort but reading through the proposed version I was not convinced that it would offer the readers a better presentation on the topic.  I thought that the changes were needed because how other reports look like.

**Comment by grahamperrin** [comment]
Thanks for the feedback, I'll revert the relevant parts as soon as I can.

**Comment by grahamperrin** [comment]
(A very interesting project, by the way!)

**Comment by grahamperrin** [comment]
I know what this means: 

> … until the Intel Wireless support becomes mature enough. …

Will the meaning be clear enough to all readers? 

Amongst the reverted suggestions: 

> Therefore, it might serve as an interim solution whilst FreeBSD matures its support for these chipsets.

**Comment by pgj** [comment]
Sure, I am fine with changes in the grammar and changing the sentences themselves.  (I am far from being a native English speaker with my Ugric linguistic heritage.)  What I would prefer instead is that please do not change the order of the sentences and the composition (hence number) of the paragraphs.

**Comment by lsalvadore** [comment]
Merged, thanks.

**Comment by grahamperrin** [comment]
Sorry, I made final suggestions with GitHub not showing me the closure. (It was a draft, intentionally.)

If you're intrested, https://github.com/freebsd/freebsd-doc/commit/263c0266486f4491e7d7e1625b1e43531d7c4642

**Pull request closed without merging**
