### PR TITLE
New committer (doc): Graham Perrin

### PR DESCRIPTION
**Pull request by grahamperrin**
Partly with reference to <https://reviews.freebsd.org/D10632> (May 2017) for Danilo G. Baio (dbaio); partly in accordance with <https://docs.freebsd.org/en/articles/committers-guide/#commit-steps> steps for new committers …

### CODE REVIEW

**Comment by grahamperrin** [comment]
NB this is not to avoid Phabricator, it's for me to (first) get my head around things.

**Comment by grahamperrin** [comment]
### Notes to self

A February 2022 example: <https://reviews.freebsd.org/D34295>, 

> Add entries for Alfonso S. Siciliano (asiciliano) · freebsd/freebsd-doc@d9e1023

----

Mine …

image

<https://wiki.freebsd.org/Phabricator#Create_a_Revision_via_command_line_.28if_using_git.29> confused me, `arc diff --create main` seemed to not work as expected. 

Instead, <https://wiki.freebsd.org/Phabricator#Create_a_Revision_via_Web_Interface> …

```text
root@mowa219-gjp4-8570p-freebsd:~ # gh repo sync grahamperrin/freebsd-doc && cd /usr/doc && gh repo sync --branch patch-7 && git -C /usr/ports pull --ff-only && git -C /usr/src pull --ff-only && cd
✓ Synced the "grahamperrin:main" branch from "freebsd:main"
✓ Synced the "patch-7" branch from grahamperrin/freebsd-doc to local repository
Already up to date.
Already up to date.
root@mowa219-gjp4-8570p-freebsd:~ # cd /usr/doc
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git fetch origin patch-1
From https://github.com/grahamperrin/freebsd-doc
 * branch                  patch-1    -> FETCH_HEAD
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git switch patch-1
branch 'patch-1' set up to track 'origin/patch-1'.
Switched to a new branch 'patch-1'
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git branch
  main
* patch-1
  patch-7
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git diff -U999999 main > /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # rm /tmp/doc-patch-1.diff 
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git commit
On branch patch-1
Your branch is up to date with 'origin/patch-1'.

nothing to commit, working tree clean
root@mowa219-gjp4-8570p-freebsd:/usr/doc # arc diff --create main
ARC: Cannot mix D and F
UNIX: No such file or directory
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git diff -U999999 main > /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # less /tmp/doc-patch-1.diff 
root@mowa219-gjp4-8570p-freebsd:/usr/doc # du -hs /tmp/doc-patch-1.diff 
1.9M    /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # 
```

* <https://reviews.freebsd.org/differential/diff/107398/> was the unwanted result of me omitting something before use of [git-diff(1)](https://www.freebsd.org/cgi/man.cgi?query=git-diff&sektion=1&manpath=FreeBSD-Ports). 

----

```text
root@mowa219-gjp4-8570p-freebsd:/usr/doc # rm /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git switch main
Switched to branch 'main'
Your branch is behind 'origin/main' by 54 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git pull
Updating f9686d822e..3cdf64c696
Fast-forward
 documentation/content/en/articles/committers-guide/_index.adoc           |   6 +--
 documentation/content/en/articles/freebsd-src-lsp/_index.adoc            |   2 +-
 documentation/content/en/articles/pgpkeys/_index.adoc                    |  28 +++++------
 documentation/content/en/books/faq/_index.adoc                           |  24 +++++----
 documentation/content/en/books/handbook/introduction/_index.adoc         |   4 +-
 documentation/content/en/books/handbook/linuxemu/_index.adoc             |   4 +-
 documentation/content/en/books/porters-handbook/plist/_index.adoc        |  12 -----
 documentation/content/en/books/porters-handbook/uses/_index.adoc         |  21 +++-----
 documentation/content/en/books/porters-handbook/versions/_index.adoc     |  19 ++++++-
 documentation/content/ja/books/handbook/basics/_index.adoc               | 151 +++++++++++++++++++++++++++++++++++++++++++++++++------
 documentation/content/ja/books/handbook/eresources/_index.adoc           |  32 +++---------
 documentation/static/pgpkeys/adridg.key                                  | 159 +++++++++++++++++++++++++++++++++++++---------------------
 documentation/themes/beastie/assets/styles/documentation.scss            |  36 +++++++++-----
 documentation/themes/beastie/assets/styles/footer.scss                   |  13 ++++-
 documentation/themes/beastie/assets/styles/global.scss                   |  30 ++++++-----
 documentation/themes/beastie/assets/styles/header.scss                   |   9 +++-
 documentation/themes/beastie/assets/styles/variables.scss                |   4 +-
 documentation/themes/beastie/layouts/partials/site-footer.html           | 118 +++++++++++++++++++++----------------------
 shared/contrib-committers.adoc                                           |   2 -
 shared/contrib-corealumni.adoc                                           |  14 ++++--
 shared/contrib-develalumni.adoc                                          |   2 +
 shared/ja/mailing-lists.adoc                                             |  76 +++++++++++-----------------
 website/archetypes/release/hardware.adoc                                 |  88 ---------------------------------
 website/content/de/where.adoc                                            | 268 ++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------
 website/content/en/administration.adoc                                   |  22 ++++-----
 website/content/en/advocacy/myths.adoc                                   |  60 +++++++++++++++-------
 website/content/en/cgi/ports.cgi                                         |   4 +-
 website/content/en/donations/donors.adoc                                 |   1 +
 website/content/en/internal/bylaws.adoc                                  |   2 +-
 website/content/en/internal/members.adoc                                 |  24 +++++----
 website/content/en/releases/13.1R/hardware.adoc                          |  95 +----------------------------------
 website/content/en/status/README                                         |  86 +++++++++++++++++++-------------
 website/content/en/status/_index.adoc                                    |   6 ++-
 website/content/en/status/report-2022-01-2022-03/_index.adoc             | 152 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 website/content/en/status/report-2022-01-2022-03/accessibility.adoc      |  20 ++++++++
 website/content/en/status/report-2022-01-2022-03/boot-performance.adoc   |  28 +++++++++++
 website/content/en/status/report-2022-01-2022-03/ci.adoc                 |  53 ++++++++++++++++++++
 website/content/en/status/report-2022-01-2022-03/clusteradm.adoc         |  49 ++++++++++++++++++
 website/content/en/status/report-2022-01-2022-03/doceng.adoc             | 100 +++++++++++++++++++++++++++++++++++++
 website/content/en/status/report-2022-01-2022-03/dpaa2.adoc              |  32 ++++++++++++
 website/content/en/status/report-2022-01-2022-03/ena.adoc                |  26 ++++++++++
 website/content/en/status/report-2022-01-2022-03/fpart.adoc              |  38 ++++++++++++++
 website/content/en/status/report-2022-01-2022-03/freebsd-foundation.adoc | 145 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 website/content/en/status/report-2022-01-2022-03/gcc.adoc                |  28 +++++++++++
 website/content/en/status/report-2022-01-2022-03/gunion.adoc             |  23 +++++++++
 website/content/en/status/report-2022-01-2022-03/hellosystem.adoc        |  28 +++++++++++
 website/content/en/status/report-2022-01-2022-03/intro.adoc              |  11 +++++
 website/content/en/status/report-2022-01-2022-03/iwlwifi.adoc            |  26 ++++++++++
 website/content/en/status/report-2022-01-2022-03/kde.adoc                |  52 +++++++++++++++++++
 website/content/en/status/report-2022-01-2022-03/ocf-wg.adoc             |  14 ++++++
 website/content/en/status/report-2022-01-2022-03/office.adoc             |  24 +++++++++
 website/content/en/status/report-2022-01-2022-03/portconfig.adoc         |  18 +++++++
 website/content/en/status/report-2022-01-2022-03/portmgr.adoc            |  51 +++++++++++++++++++
 website/content/en/status/report-2022-01-2022-03/pot.adoc                |  23 +++++++++
 website/content/en/status/report-2022-01-2022-03/releng.adoc             |  21 ++++++++
 website/content/en/status/report-2022-01-2022-03/rtw88.adoc              |  24 +++++++++
 website/content/en/status/report-2022-01-2022-03/wifibox.adoc            |  31 ++++++++++++
 website/content/en/where.adoc                                            |  19 ++++---
 website/content/es/where.adoc                                            | 270 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------
 website/content/fr/internal/bylaws.adoc                                  |   4 +-
 website/content/fr/where.adoc                                            |  12 ++---
 website/content/hu/where.adoc                                            | 351 ++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------------
 website/content/it/where.adoc                                            | 352 ++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------------------
 website/content/ja/where.adoc                                            |  12 ++---
 website/content/nl/where.adoc                                            | 225 +++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------
 website/content/ru/internal/bylaws.adoc                                  |   4 +-
 website/content/ru/where.adoc                                            | 344 +++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------------
 website/content/zh-cn/where.adoc                                         | 336 ++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------------------------
 website/content/zh-tw/where.adoc                                         | 320 ++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------------
 website/data/en/news/news.toml                                           |  10 ++++
 website/data/en/usergroups/usergroups.toml                               |   7 ---
 website/data/en/vendors/isp.toml                                         |   6 ---
 website/data/ja/news/news.toml                                           |  26 +++++++---
 website/themes/beastie/i18n/de.toml                                      |   3 ++
 website/themes/beastie/i18n/en.toml                                      |   3 ++
 website/themes/beastie/i18n/es.toml                                      |   3 ++
 website/themes/beastie/i18n/fr.toml                                      |   3 ++
 website/themes/beastie/i18n/ja.toml                                      |   3 ++
 website/themes/beastie/i18n/nl.toml                                      |   3 ++
 website/themes/beastie/i18n/ru.toml                                      |   3 ++
 website/themes/beastie/i18n/zh-cn.toml                                   |   3 ++
 website/themes/beastie/i18n/zh-tw.toml                                   |   3 ++
 website/themes/beastie/layouts/partials/site-navigation.html             |   3 ++
 83 files changed, 2833 insertions(+), 1934 deletions(-)
 create mode 100644 website/content/en/status/report-2022-01-2022-03/_index.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/accessibility.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/boot-performance.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/ci.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/clusteradm.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/doceng.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/dpaa2.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/ena.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/fpart.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/freebsd-foundation.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/gcc.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/gunion.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/hellosystem.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/intro.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/iwlwifi.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/kde.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/ocf-wg.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/office.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/portconfig.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/portmgr.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/pot.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/releng.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/rtw88.adoc
 create mode 100644 website/content/en/status/report-2022-01-2022-03/wifibox.adoc
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git switch patch-1
Switched to branch 'patch-1'
Your branch is up to date with 'origin/patch-1'.
root@mowa219-gjp4-8570p-freebsd:/usr/doc # arc diff --create main
ARC: Cannot mix D and F
UNIX: No such file or directory
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git diff -U999999 main > /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # du -hs /tmp/doc-patch-1.diff
440K    /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # 
```

* wrong again
* <https://reviews.freebsd.org/differential/diff/107399/> can be deleted.

----

image

image

image

```text
root@mowa219-gjp4-8570p-freebsd:/usr/doc # rm /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git branch
  main
* patch-1
  patch-7
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), 1.95 KiB | 142.00 KiB/s, done.
From https://github.com/grahamperrin/freebsd-doc
   83ff5713a5..719b0449e4  patch-1    -> origin/patch-1
Updating 83ff5713a5..719b0449e4
Fast-forward
 documentation/content/en/books/handbook/introduction/_index.adoc |   2 +-
 website/content/de/where.adoc                                    | 268 +++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------
 website/content/en/advocacy/myths.adoc                           |  60 +++++++++++++++++-------
 website/content/en/where.adoc                                    |  19 +++++---
 website/content/es/where.adoc                                    | 270 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------
 website/content/fr/where.adoc                                    |  12 ++---
 website/content/hu/where.adoc                                    | 351 +++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------------------
 website/content/it/where.adoc                                    | 352 +++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------------------
 website/content/ja/where.adoc                                    |  12 ++---
 website/content/nl/where.adoc                                    | 225 ++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------
 website/content/ru/where.adoc                                    | 344 ++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------------------
 website/content/zh-cn/where.adoc                                 | 336 ++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------------------------------------
 website/content/zh-tw/where.adoc                                 | 320 +++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------------
 13 files changed, 1201 insertions(+), 1370 deletions(-)
root@mowa219-gjp4-8570p-freebsd:/usr/doc # git diff -U999999 main > /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # du -hs /tmp/doc-patch-1.diff
132K    /tmp/doc-patch-1.diff
root@mowa219-gjp4-8570p-freebsd:/usr/doc # less /tmp/doc-patch-1.diff 
root@mowa219-gjp4-8570p-freebsd:/usr/doc # 
```

* success
* <https://reviews.freebsd.org/differential/diff/107401/>
* <https://reviews.freebsd.org/D35603>

> ⚙ D35603 New committer (doc): Graham Perrin, grahamperrin@

**Comment by grahamperrin** [comment]
### Reference

```text
Date: Wed, 1 Jun 2022 20:41:20 -0300
From: "Danilo G. Baio" <dbaio@…>
To: grahamperrin@…, gjb@…, carlavilla@…
Cc: core@…, accounts@…, doceng@…
Subject: New doc commit bit for Graham Perrin
…
```

**Comment by grahamperrin** [comment]
▶ https://reviews.freebsd.org/D35603

**Comment by grahamperrin** [comment]
From hidden comment <https://github.com/freebsd/freebsd-doc/pull/80/#issuecomment-1166478970> above: 

> … `arc diff --create main` seemed to not work as expected. …

Maybe FreeBSD bug [264852 – devel/arcanist: arc diff --create error](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264852), which I subscribed to yesterday and then (oops) had no memory of less than twenty-four hours later `:-)`

**Comment by dbaio** [comment]
Hi.
You are using Phabricator with your mentors, why duplicate the work here?

**Comment by grahamperrin** [comment]
Hi, 

> … why duplicate the work here?

Above, 

>> NB this is not to avoid Phabricator, it's for me to (first) get my head around things.

This pull request came first, for my sanity, whilst learning, because I'm accustomed to workflow with GitHub. <https://reviews.freebsd.org/p/grahamperrin/> (blurb added a few minutes ago); _dyslexia_ …

**Comment by dbaio** [comment]
Got it; thanks for clarifying, and keep doing whatever you need. 
I'm not your mentor, but if you need anything, you can also reach me.

**Comment by grahamperrin** [comment]
@dbaio many thanks 👍

**Pull request closed without merging**
