### PR TITLE
Updated out-of-date software name(Homura to Suyimazu)

### PR DESCRIPTION
**Pull request by duckyondiscord**

### CODE REVIEW

**Comment by sergio-carlavilla** [comment]
Thanks, I'll take a look at merge it!

**Comment by sergio-carlavilla** [comment]
But we need to change all the occurrences of Homura, can you please provide a patch?

**Comment by duckyondiscord** [comment]
> But we need to change all the occurrences of Homura, can you please provide a patch?

I wasn't aware of it occurring more than one time, I'll take a look.

**Comment by sergio-carlavilla** [comment]
Sorry, I forgot to tell you that the changes need to be made at the _index.adoc file, the .po files are generated automatically.

**Comment by duckyondiscord** [comment]
> Sorry, I forgot to tell you that the changes need to be made at the _index.adoc file, the .po files are generated automatically.

Well I did both of them, I wasn't aware, sorry.

**Comment by duckyondiscord** [comment]
I only changed the parts that I knew wouldn't affect functionality, so filenames are still using homura.

**Comment by duckyondiscord** [comment]
> Perfect, one last thing, what's your name and email? for the commit
> Send your email to me privately: carlavilla@FreeBSD.org
> 
> I don't know why but github remove it

Sent :)

**Comment by sergio-carlavilla** [comment]
Fixed in: https://cgit.freebsd.org/doc/commit/?id=cec5f13450b741bfec390c83b37eed970545190b

Thanks!

**Pull request closed without merging**
