### PR TITLE
el: obsolete pkg_add -r command and Adobe Flash

### PR DESCRIPTION
**Pull request by chrislongros**
obsolete pkg_add -r command and Adobe Flash

https://support.mozilla.org/en-US/kb/end-support-adobe-flash

### CODE REVIEW

**Review by igalic — APPROVED** [review]
looks plausible!

**Comment by chrislongros** [comment]
> looks plausible!

I have many changes in mind. I just don't know who can merge my pull requests as the greek team doesn't seem that active..

**Comment by sergio-carlavilla** [comment]
I'll do the commit :)

**Comment by sergio-carlavilla** [comment]
Commit in: https://cgit.freebsd.org/doc/commit/?id=49ef67a9b7cf507e441809fb176dc76def40f166

**Pull request closed without merging**
