### PR TITLE
typo?

### PR DESCRIPTION
**Pull request by qtfkwk**

### CODE REVIEW

**Review by chrislongros — APPROVED** [review]
Yes, ifconfig_wlan0="WPA DHCP" itself is no command :)

**Comment by dbaio** [comment]
Hello.

Thanks for your contribution.

To properly register your contribution, we will need your e-mail and name. This is what we are receiving [at this moment](https://patch-diff.githubusercontent.com/raw/freebsd/freebsd-doc/pull/301.patch):

```
qtfkwk <qtfkwk@users.noreply.github.com>
```

Alternatively, if you prefer not to share your email, that's perfectly fine. We can simply add a line like this in the commit message:

```
Submitted by:    your name or username
```

Just let us know what you prefer.

Regards.

**Comment by chrislongros** [comment]
My email address is ***@***.*** and my name is Christos Longros

**Comment by qtfkwk** [comment]
`Submitted by: qtfkwk` works. Thanks!

**Comment by dbaio** [comment]
Committed on 879f78ad1b0ca6177bb02062732c8a91d7f4b804
Thank you!

**Pull request closed without merging**
