### PR TITLE
Status: 2023q3: doceng: corrections, markup

### PR DESCRIPTION
**Pull request by grahamperrin**
Chronology: this quarter, not last. This quarter is the third.

Markup: 

* `--` for em dashes, where appropriate
* remove unnecessary white space before list items
* add missing markup for list items – compare with [the Team's report for the first quarter of this year](https://www.freebsd.org/status/report-2023-01-2023-03/#_documentation_engineering_team).

**Real names** for people who requested safekeeping of their commit bits – compare with the same past report

* more human, less robotic.

~~Include the resignation of my doc commit bit. Express this in the same way as the safekeeping of Sergey Kandaurov's doc commit bit.~~ ✅ Done.

The new Weblate server was a server, not a person (should not be amongst the list of humans who perform translation).

Moreover: the Weblate server was new in April (last quarter, not this quarter). So, don't repeat the news.

Fix five URLs:

* side note, I have seen the breaking `url` appends to URLs in the past, I wonder whether they're the result of something that's automated or scripted.

Miscounts:

* three is not four
* four is not three.

Uppercase `USES` for technical accuracy (not `Uses`), exemplify `USES=…` for consistency with all instances within the relevant handbook (not `USES =…` with an additional white space), and no need to repeat the word 'New'.

Consistency:

* if some headings will be Americanised (according to guidance for status reports), then Americanise all.

Punctuation: 

* paragraphs that are not list items should end with a full stop
* a heading need not end with a colon if the subsequent line (the beginning of a normal paragraph) has a trailing colon
* ⋯

### CODE REVIEW

**Review by lsalvadore — APPROVED** [review]
Approved if someone in doceng also approves. @sergio-carlavilla? @dbaio?

**Comment by sergio-carlavilla** [comment]
No, I prefer the report sent by fernape@

**Comment by lsalvadore** [comment]
Ok, then this pull request can be closed.

@grahamperrin: Please note that your commit bit resignation was already added with commit 1687289.

**Comment by grahamperrin** [comment]
> Add missing markup, for list items. Compare with [the Team's report for the first quarter of this year](https://www.freebsd.org/status/report-2023-01-2023-03/#_documentation_engineering_team).

A visual comparison might help. Please note, use of bullet points: 

image

The current edition of this quarter's report lacks the bullet points: 

image

**Comment by sergio-carlavilla** [comment]
No, keep it as it.

**Comment by grahamperrin** [comment]
> No, keep it as it.

Do you mean, keep the broken links and other issues?

**Comment by grahamperrin** [comment]
Maybe I misunderstood. 

@sergio-carlavilla do you mean, keep this pull request closed (keep it as is) and make a new pull request? 

The [GitHub view of the current edition](https://github.com/freebsd/freebsd-doc/blob/7bf022d23a57c65309cb3648984a34ae6b4ce229/website/content/en/status/report-2023-07-2023-09/doceng.adoc) 7bf022d23a57c65309cb3648984a34ae6b4ce229 should be reasonably clear, clear enough to see some of what remains to be fixed. If not clear in GitHub, this PDF might help: 

[doceng-7bf022d23a57c65309cb3648984a34ae6b4ce229.pdf](https://github.com/freebsd/freebsd-doc/files/12787485/doceng-7bf022d23a57c65309cb3648984a34ae6b4ce229.pdf)

**Comment by sergio-carlavilla** [comment]
Go ahead, I'm gonna reopen the PR

**Review by grahamperrin — COMMENTED** [review]
Please see the two most recent commit messages.

Re: the discrepancies, are my assumptions true?

In particular, I don't know about the people who translate; whether all four of them are _truly_ new.

(Bear in mind, the news about the Weblate server, which might have been a copy-and-paste error from a past report.)

**Comment by sergio-carlavilla** [comment]
@lsalvadore make the commit please.

**Comment by lsalvadore** [comment]
Commit done, thanks.

**Pull request closed without merging**
