### PR TITLE
Update _index.adoc

### PR DESCRIPTION
**Pull request by steel-2**
Changed "ant" to "and" in the "Connection and Authentication to a Wireless Network" Section.

### CODE REVIEW

**Comment by sergio-carlavilla** [comment]
Thank you! With what name and email do you want us to make the commit?

**Comment by steel-2** [comment]
Hi Sergio,

It was my pleasure. I am new to FreeBSD, and I am glad to contribute.

My name is Aaron Baynard
and my is ***@***.***

**Comment by sergio-carlavilla** [comment]
I don't know why but Github it's not showing your email.
Can you please share it with me by email? carlavilla@FreeBSD.org

**Comment by sergio-carlavilla** [comment]
Fixed in: https://cgit.freebsd.org/doc/commit/?id=30e851c8dbad67d08eefaddeec37cdc7c4e65c36

Thanks and sorry for the delay!

**Pull request closed without merging**
