### PR TITLE
status report call template: earlier (not earliest)

### PR DESCRIPTION
**Pull request by grahamperrin**

### CODE REVIEW

**Comment by grahamperrin** [comment]
@lsalvadore ▲ for your consideration, thanks.

**Review by lsalvadore — APPROVED** [review]
Approved, thanks!

**Comment by grahamperrin** [comment]
### Notes to self

Graham, don't accidentally work on the `main` branch of your fork: 

image

– **and** then (without committing what's above) attempt to use Git at the command line for a _later_ commit: 

image

… et cetera, and now: 

image

I really shouldn't be laughing at myself, but … :-)

----

Fingers crossed, I'll untangle this without requiring assistance

**Comment by grahamperrin** [comment]
> … Fingers crossed, I'll untangle this without requiring assistance

Untangled: 

* https://gist.github.com/grahamperrin/a034e16a222e0e8f092c0842b944451b

– thanks to `@FUZxxl:libera.chat` for some pointers.

**Pull request closed without merging**
