### PR TITLE
Fixing typo in _index.adoc

### PR DESCRIPTION
**Pull request by slash071**
Typo fix in _index.adoc. Duplicated words were used and one has been removed.

### CODE REVIEW

**Comment by grahamperrin** [comment]
Thank you! 

Committed locally, not yet pushed to `freebsd main`: 

```text
commit be041bea79aa1b1d391e6d10e8bdc27bd37dce55 (HEAD -> main)
Author: Graham Perrin <grahamperrin@FreeBSD.org>
Date:   Mon Jul 10 05:53:40 2023 +0100

    FreeBSD Handbook: fix and improve a pair of warnings
    
    Installing Applications: Packages and Ports – Overview of Software
    Installation – Warning
    
    Fix the word doubling (use use) that was found by Mohammadreza in the
    second warning in db3bba9456.
    
    Whilst here:
    
    - make the first of the two warnings more concise
    
    - reword the second warning, to be consistent with the NAME of
      pkg-audit(8).
    
    Reported-by:  Mohammadreza (GitHub user slash071)
    Fixes:        db3bba9456 handbook: Wordsmith a fragment about pkg-audit(8)
    Pull-request: https://github.com/freebsd/freebsd-doc/pull/216
% 
````

**Comment by grahamperrin** [comment]
Pushed. Thanks again

**Comment by slash071** [comment]
You're welcome. There are some other typos too; I will create a pull request again for it.

**Comment by slash071** [comment]
Okay, there was a typo so, I decided not to create a new pull request for it and report it here again.

Here is the type:  
`files/:` which should be `files:`  and here is the [location](https://github.com/freebsd/freebsd-doc/blob/main/documentation/content/en/books/handbook/ports/_index.adoc?plain=1#L658). (Actually `/` is redundant and should be removed)

Also, there were lines that had more than one space between words, which I thought it might be for better readability and I didn't include them here.

**Comment by slash071** [comment]
He, I forgot there are word that used `s` instead of `z` like `virtualisation`. I guess the guy who wrote this was from England, LoL. Do you want me to open a pull request?

**Pull request closed without merging**
