### PR TITLE
status: 2023q2: Wazuh: markup and other changes

### PR DESCRIPTION
**Pull request by grahamperrin**

### CODE REVIEW

**Comment by grahamperrin** [comment]
[Line 24](https://github.com/freebsd/freebsd-doc/pull/213/files#diff-67b31c4265b362da6cd11f8ea08b65ee74c338e22f24029033d857ad5d53aadeR24), I can not tell what is meant by 'It'.

**Comment by lsalvadore** [comment]
> [Line 24](https://github.com/freebsd/freebsd-doc/pull/213/files#diff-67b31c4265b362da6cd11f8ea08b65ee74c338e22f24029033d857ad5d53aadeR24), I am not sure what is meant by 'It'.

I think it means the set of Wazuh components. I guess it should be phrased better. Feel free to submit a better rewording and consider it approved by me if it is also approved by the original author.

Thanks.

**Review by lsalvadore — APPROVED** [review]

**Comment by grahamperrin** [comment]
> I think it means …

FreshPorts to the rescue. Result: [`2ab0ff8` (#213)](https://github.com/freebsd/freebsd-doc/pull/213/commits/2ab0ff8ff1565faba7dec86bf24fcb1edc4410b1)

----

If I do not find José Alonso Cárdenas Márquez in chat anywhere, I'll ping him via email.

**Comment by grahamperrin** [comment]
`acm` found in Matrix, I pinged him with reference to this PR.

**Comment by pauamma** [comment]
> `acm` found in Matrix, I pinged him with reference to this PR.

If you don't get an answer (or that's the wrong one) I still have an email address for him.

**Comment by grahamperrin** [comment]
> If you don't get an answer (or that's the wrong one) I still have an email address for him.

Thanks. 

It's a confirmed Matrix ID on the dev server, the address of which was recently disclosed in IRC (surprisingly … I thought that people might wait for a status report from the Core team before disclosing).

**Comment by alonsobsd** [comment]
@grahamperrin I agree with your changes. Just note a minor change there

"Currently, all Wazuh components are ported: package:security/wazuh-manager[], package:security/wazuh-agent[], package:security/wazuh-server[], package:security/wazuh-indexer[], and package:security/wazuh-dashboard[]."

Perphaps we could change it to "Currently, all Wazuh components are ported or adapted: ..."

Really not all components were ported because I adapted wazuh-dashboard and wazuh-indexer ports using opensearch and opensearch-dashboards apps. Wazuh project forked those projects (currently from 2.6.0) for create their own versions but they applied just minor changes (login including Wazuh logo for example, changes some configuration paths, etc) but they have the same opensearch functionalities.

**Pull request closed without merging**
