### PR TITLE
Update _index.adoc

### PR DESCRIPTION
**Pull request by MilkGolium**
Package name changed.
图片

### CODE REVIEW

**Comment by MilkGolium** [comment]
OK, I've sent the email

**Comment by sergio-carlavilla** [comment]
Sorry, I got it, yes, btw the name is not iridium-desktop is iridium-browser
Btw, I'm gonna make the commit and put your name as author since you raised the bug and provide a patch

**Comment by MilkGolium** [comment]
OK，thank you!

**Comment by MilkGolium** [comment]
Thank you! I am happy to do something for FreeBSD. 🙂

Sergio Carlavilla ***@***.***> 于2023年9月15日周五 18:42写道：

**Comment by grahamperrin** [comment]
> Handbook - Desktop: Fix iridium package name · freebsd/freebsd-doc@28225ea

**Pull request closed without merging**
