### PR TITLE
Remove out of date info

### PR DESCRIPTION
**Pull request by linimon**
Remove a reference that is over a decade out of date.

### CODE REVIEW

**Comment by pauamma** [comment]
@dbaio or someone from a translation team, correct me if I'm wrong, but IIRC that file is automatically generated from documentation/content/en/books/arch-handbook/driverbasics/_index.adoc, which is the one to modify instead, and still has that reference as I'm writing this.

**Comment by emaste** [comment]
@dbaio correct the .adoc file needs to be updated

**Comment by sergio-carlavilla** [comment]
I'm gonna make the change and push it to the repo.
I'll give the credit to linimon@ :)

**Comment by sergio-carlavilla** [comment]
Done: https://cgit.freebsd.org/doc/commit/?id=c73262b816dfa20fee25cb9c355180e7a62bd610
Thanks!

**Comment by emaste** [comment]
Thanks Sergio!

**Pull request closed without merging**
