### PR TITLE
Update _index.adoc

### PR DESCRIPTION
**Pull request by distancesprinter**
Trivial change level example for consistency with prior section

### CODE REVIEW

**Comment by dbaio** [comment]
Hello.

Thanks for your contribution.

To properly register your contribution, we will need your e-mail and name. This is what we are receiving [at this moment](https://patch-diff.githubusercontent.com/raw/freebsd/freebsd-doc/pull/344.patch):

```
distancesprinter <distancesprinter@users.noreply.github.com>
```

Alternatively, if you prefer not to share your email, that's perfectly fine. We can simply add a line like this in the commit message:

```
Submitted by:    your name or username
```

Just let us know what you prefer.

Regards.

**Comment by distancesprinter** [comment]
Hi.

You're welcome to attribute my commit as follows:

Submitted by:    Matt Viverette

Will you somehow link my Github user ID to that message, or should I be
sure to add a line like that to any future pull requests?  I am a bit of a
Github noob and haven't made many contributions, but having a correction
accepted to the FreeBSD FDP primer, albeit trivial, does make me feel
special.

Have a good day.

**Comment by dbaio** [comment]
If you provide an email and add it to your GitHub account, this commit will be linked. Otherwise, the credits will only be mentioned in the commit message.
For future PRs, which are very welcome, the process will be easier and simpler, with automatic crediting.
Thank you, and have a good day too.

**Comment by dbaio** [comment]
Committed on https://github.com/freebsd/freebsd-doc/commit/e38dc93e5ad71a12ece68539a14be36662014621
Thank you!

**Pull request closed without merging**
