### PR TITLE
Committer's Guide: four tiers: heading levels

### PR DESCRIPTION
**Pull request by grahamperrin**
Level 3 section title for tiers 1, 2, and 3, and for the unsupported tier.

### CODE REVIEW

**Comment by bsdimp** [comment]
I think this is good, but I'm not a doc person.

**Comment by grahamperrin** [comment]
To help readers visualise the proposed change, here's the level 2 section heading that precedes the change: 

* [before](https://docs.freebsd.org/en/articles/committers-guide/#_platform_targets) (live)
* [after](https://github.com/grahamperrin/freebsd-doc/blob/patch-9/documentation/content/en/articles/committers-guide/_index.adoc#212-platform-targets) (preview in GitHub). 

Strictly speaking, the L3 headings for the four tiers should be preceded by a L2 heading that includes (or comprises) the word _tiers_. I can easily move and change some texts, a little, to improve the order and sense of things, but first: 

* let's consider the four headings alone. 

----

I began this PR because [the intent describes **four** tiers](https://docs.freebsd.org/en/articles/committers-guide/#_statement_of_general_intent) and looking at headings, I counted only **three** – three that are _numbered_. 

Essentially: 

* is _unsupported_ a tier, or not a tier? 

I can see that it was previously a numbered tier, but now, it's like a fourth tier without a number. 

Has the sentence below become untrue? 

> The FreeBSD Project differentiates platform targets into four tiers.

**Comment by bsdimp** [comment]
Tier 4 is everything not supported. It seemed silly to number it when we revised the tier system 10ish years ago.

**Comment by emaste** [comment]
LGTM

**Pull request closed without merging**
