### PR TITLE
2023Q3 status report for Wifibox

### PR DESCRIPTION
**Pull request by pgj**
This is a status report for the [FreeBSD Wifibox project](https://github.com/pgj/freebsd-wifibox) in the FreeBSD Ports Collection, for 2023Q3.

### CODE REVIEW

**Comment by sergio-carlavilla** [comment]
I'll improve the Ascidoc syntax on commit, np with that Lorenzo

**Review by lsalvadore — APPROVED** [review]
Formatting needs to be fixed, but content is approved.
Thanks for your report.

**Comment by sergio-carlavilla** [comment]
I'm gonna make it and then I'll close the report

**Comment by sergio-carlavilla** [comment]
Done: https://cgit.freebsd.org/doc/commit/?id=a33f54518f68fd3fbfa12dbade470e0ba4cdd272

**Pull request closed without merging**
