### PR TITLE
removed invalid ports copyright link

### PR DESCRIPTION
**Pull request by jdpc86**
per https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270229, removed invalid ports link for now

### CODE REVIEW

**Comment by grahamperrin** [comment]
Thanks. A Wayback Machine capture of the linked file (ASCII text): 

* <https://web.archive.org/web/20121224063547/http://www.freebsd.org/copyright/LEGAL>

**Comment by sergio-carlavilla** [comment]
@jdpc86 With which user<email> do you want me to mention you in the commit?

**Comment by dbaio** [comment]
@jdpc86 

Hello.

Thanks for your contribution.

To properly register your contribution, we will need your e-mail and name. This is what we are receiving [at this moment](https://patch-diff.githubusercontent.com/raw/freebsd/freebsd-doc/pull/130.patch):

```
jdpc86 <jdpc86@users.noreply.github.com>
```

Or if you don't want to share your e-mail, no worries. We can just add a line like this in the commit message:

```
Submitted by:    your name or username
```

You can also sign your work, first read https://developercertificate.org/ and
if you agree, add a line like this at the end of your commit message (or as a comment here):

  Signed-off-by:     John Doe <johndoe@example.com>


Just tell us what you prefer.

The same for https://github.com/freebsd/freebsd-doc/pull/128 and https://github.com/freebsd/freebsd-doc/pull/129

Regards.

**Comment by jdpc86** [comment]
Hey here is my email jdpc86.li@gmail.com, my name is Jindong Li...

**Comment by sergio-carlavilla** [comment]
Fixed in: https://cgit.freebsd.org/doc/commit/?id=abaadd1b2d7e84d968a2e070adb8da0a97fec864
Thanks!

**Pull request closed without merging**
