### PR TITLE
status: 2023q2: releng: minor changes

### PR DESCRIPTION
**Pull request by grahamperrin**
Grammar: 'the 13-2RELEASE.' and 'published publicly'.

Other changes, minor.

### CODE REVIEW

**Comment by grahamperrin** [comment]
@evilgjb

**Review by lsalvadore — APPROVED** [review]
Approved if re@ (@evilgjb , @cperciva or any other member) also approves.

**Comment by cperciva** [comment]
LGTM.

**Comment by grahamperrin** [comment]
Committed locally, not yet pushed to `freebsd main`. 

```text
% git -C /usr/doc log -n 1 --oneline
1077d362b6 (HEAD -> main) status: 2023q2: releng: minor changes
% 
```

**Pull request closed without merging**
