### PR TITLE
handbook: fix typo for WINE

### PR DESCRIPTION
**Pull request by KatyushaScarlet**
1. `... an entire other computer ...` -> `... an entirely separate computer ...`
2. `virtualizaton` -> `virtualization`
3. `... for on FreeBSD` -> `... for using WINE on FreeBSD`
4. `backed` -> `backend`
5. `addtion` -> `addition`
6. `However, than the _emulators_ section...` -> `However, instead of looking in the _emulators_ section ...`
7. `... have an prefix ...` -> `... have a prefix ...`
This is from the Advanced UNIX Programming Course (Fall’23) at NTHU.

### CODE REVIEW

**Review by chrislongros — APPROVED** [review]
Seems right!

**Comment by KatyushaScarlet** [comment]
@lwhsu Hi, can you approve my pull request?

**Comment by sergio-carlavilla** [comment]
Sorry, I'll make the commit tomorrow without fail. I've been moving to another house :)

**Comment by dbaio** [comment]
Committed on bc7fb9f5208ad08279434bb8433281b54f0a4266. Thanks for your contribution.

**Pull request closed without merging**
