### PR TITLE
handbook: fix typo for ZFS

### PR DESCRIPTION
**Pull request by KatyushaScarlet**
There's a redundant backticks here.
This is from the Advanced UNIX Programming Course (Fall’23) at NTHU.

### CODE REVIEW

**Review by igalic — CHANGES_REQUESTED** [review]
see, https://github.com/freebsd/freebsd-src/pull/951#issuecomment-1869693910 or any other similar submissions from your colleagues that have been reviewed & merged.

please change your commit messages to

```
handbook: Fix typo for ZFS

There's a redundant backtick here.

Event: Advanced UNIX Programming Course (Fall’23) at NTHU
```

**Comment by KatyushaScarlet** [comment]
> see, [freebsd/freebsd-src#951 (comment)](https://github.com/freebsd/freebsd-src/pull/951#issuecomment-1869693910) or any other similar submissions from your colleagues that have been reviewed & merged.
> 
> please change your commit messages to
> 
> ```
> handbook: Fix typo for ZFS
> 
> There's a redundant backtick here.
> 
> Event: Advanced UNIX Programming Course (Fall’23) at NTHU
> ```

OK, fixed.

**Comment by KatyushaScarlet** [comment]
@lwhsu Hi, can you help me merged my pull request?

**Review by lwhsu — APPROVED** [review]

**Comment by dbaio** [comment]
Committed on bc671a8e995421edce66c65b18b5268f5797ffe4
Thanks.

**Pull request closed without merging**
