### PR TITLE
committers-guide: Update SPDX links

### PR DESCRIPTION
**Pull request by jlduran**

### CODE REVIEW

**Comment by jlduran** [comment]
Tangentially related:
I cannot find the information about the importance of the `-` symbol preceding the license block.
Is it used to find the license block when auditing licensing information or something similar?

**Comment by bsdimp** [comment]
> Tangentially related: I cannot find the information about the importance of the `-` symbol preceding the license block. Is it used to find the license block when auditing licensing information or something similar?

Once, long ago, indent(3) would not touch comments starting with /*-. But not too many people used it. Fast forward to the 90s or early 2000s. I wrote a crappy tool to parse out license statements. It was super ugly perl and super slow. So I repurposed that as a marker, convinced the project to adopt it and touched almost every file in the tree. The parser was faster, but I couldn't get it released. I think nobody else ever used it.

So, it's officially part our guides. But it could be dropped in new stuff..

**Comment by jlduran** [comment]
> > Tangentially related: I cannot find the information about the importance of the `-` symbol preceding the license block. Is it used to find the license block when auditing licensing information or something similar?
> 
> Once, long ago, indent(3) would not touch comments starting with /*-. But not too many people used it. Fast forward to the 90s or early 2000s. I wrote a crappy tool to parse out license statements. It was super ugly perl and super slow. So I repurposed that as a marker, convinced the project to adopt it and touched almost every file in the tree. The parser was faster, but I couldn't get it released. I think nobody else ever used it.
> 
> So, it's officially part our guides. But it could be dropped in new stuff..

Wonderful info! My main issue with it was adapting it to other languages, more specifically, lua (`---`?), I've seen it in some shell scripts (and atf-sh scripts) as well (`#-`). Knowing where it came from and that it can be omitted is good to know, thank you!

**Comment by jlduran** [comment]
Found it!

For my future reference:

https://github.com/freebsd/freebsd-src/commit/9ddb49cbe45441fa3f3a10f6dd355e9956480b5f

Remember to also include man pages.

**Review by concussious — APPROVED** [review]
Thanks for doing this!

**Comment by dbaio** [comment]
Committed on https://github.com/freebsd/freebsd-doc/commit/a2ae4bf5ae1cdf5ebe7ee6dd9b871a3087bd78c9
Thank you!

**Pull request closed without merging**
