### PR TITLE
Add example of port FLAVOR notation in poudriere port-list

### PR DESCRIPTION
**Pull request by garrettboone**

### CODE REVIEW

**Comment by garrettboone** [comment]
This is a first-time contribution - I'm not clear on whether the related po file is somehow automatically generated, a product of the translation site, or also needs a corresponding edit.

**Comment by sergio-carlavilla** [comment]
Hi,
To make the commit I need a name and an email.

Can you please share if by email with me? carlavilla@FreeBSD.org

**Comment by garrettboone** [comment]
> Hi, To make the commit I need a name and an email.
> 
> Can you please share if by email with me? [carlavilla@FreeBSD.org](mailto:carlavilla@FreeBSD.org)

Email was sent, thanks.

**Comment by sergio-carlavilla** [comment]
Fixed in: https://cgit.freebsd.org/doc/commit/?id=2d8291224c4fe79182c92e3b6a7e3de91208c9b1

I made a little tweak, instead of using a absolute link we use a macro for links to another books.

Btw, the commit is made in your name :)

**Pull request closed without merging**
